export const types = {
  GET_RANDOM_PSALM: 'GET_RANDOM_PSALM',
  SET_SELECTED_TEXT: 'SET_SELECTED_TEXT',
  GET_FAVORITE_PSALMS: 'GET_FAVORITE_PSALMS',
  SET_FAVORITE_PSALMS: 'SET_FAVORITE_PSALMS',
  GET_SAVED_VERSES: 'GET_SAVED_VERSES',
  SET_SAVED_VERSES: 'SET_SAVED_VERSES',
};
